# Generated by Django 3.2.4 on 2021-06-25 07:56

from django.db import migrations
from tsetmc.client.utils import populate_db


def populate_stock_table(app, _):
    Stock = app.get_model('tsetmc', 'Stock')
    populate_db(Stock)


class Migration(migrations.Migration):
    dependencies = [
        ('tsetmc', '0002_auto_20210625_1220'),
    ]

    operations = [
        migrations.RunPython(populate_stock_table,
                             reverse_code=migrations.RunPython.noop)
    ]
