"""
Django settings for Stocker project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import environ  # noqa

from pathlib import Path
from celery.schedules import crontab

env = environ.Env(

    DEBUG=(bool, False)
)
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rp80w%g6o0_26$!s=%2-j^tvf9)+)7$y-lk#--j*gqlxog2i8_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_celery_results',
    'django_celery_beat',

    'tsetmc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Stocker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Stocker.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'stocker',
        'USER': env('DB_USER', default='stocker'),
        'PASSWORD': env('DB_PASSWD', default='stocker'),
        'HOST': 'localhost'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = './front-end'
MEDIA_ROOT = './media/'
MEDIA_URL = '/media/'

GMAIL_USERNAME = env('GMAIL_USERNAME')
GMAIL_PASSWORD = env('GMAIL_PASSWORD')

CELERY_ANALYSIS_SCHEDULE = crontab(hour=15, minute=0, day_of_week=[0, 1, 2, 3, 6]),  # sun, mon, tue, wed, sat

CELERY_BROKER_URL = f"redis://127.0.0.1:{env('REDIS_PORT', default='6379')}"
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ['pickle', 'application/json']
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tehran"

DATA_PATH = os.path.join(BASE_DIR, 'data')
STOCKS_PRICE_DATA_PATH = os.path.join(DATA_PATH, 'stock_prices')
STOCKS_CLIENT_TYPE_DATA_PATH = os.path.join(DATA_PATH, 'client_type_prices')
STOCKS_SHAREHOLDERS_DATA_PATH = os.path.join(DATA_PATH, 'shareholders')
STOCK_DETAILS_FILEPATH = os.path.join(DATA_PATH, 'stocks_details.json')

TSE_STOCK_DETAILS_URL = \
    "http://tsetmc.com/Loader.aspx?ParTree=151311&i={ticker_index}"
TSE_STOCK_PRICE_DATA__FILE_URL = \
    "http://tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i={ticker_index}"
TSE_STOCK_CLIENT_TYPE_DATA_FILE_URL = \
    "http://www.tsetmc.com/tsev2/data/clienttype.aspx?i={ticker_index}"
TSE_STOCK_SHAREHOLDERS_DATA_URL = \
    "http://www.tsetmc.com/Loader.aspx?Partree=15131T&c={instrument_id}"
TSE_STOCKS_URL = \
    'http://www.tsetmc.com/Loader.aspx?ParTree=15131F'
