# Generated by Django 3.2.4 on 2021-06-25 07:50

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.core.management.sql import emit_post_migrate_signal


def create_superuser(app, _):
    User = app.get_model('auth.User')
    data = {
        'username': 'mrafee113',
        'first_name': 'Mehdi',
        'last_name': 'Rafee',
        'email': 'mrafee113@gmail.com',
        'is_staff': True,
        'is_active': True,
        'is_superuser': True,
        'password': make_password('jeez'),
    }
    if not User.objects.filter(username='mrafee113').exists():
        user = User.objects.create(**data)


def create_analyst_group(app, _):
    emit_post_migrate_signal(2, False, 'default')
    Group = app.get_model('auth.Group')
    Permission = app.get_model('auth', 'Permission')

    data = {'name': 'Analysts'}
    permission_codenames = [
        ("add_clockedschedule", "django_celery_beat"),
        ("view_clockedschedule", "django_celery_beat"),
        ("add_crontabschedule", "django_celery_beat"),
        ("view_crontabschedule", "django_celery_beat"),
        ("add_intervalschedule", "django_celery_beat"),
        ("view_intervalschedule", "django_celery_beat"),
        ("add_periodictask", "tsetmc"),
        ("change_periodictask", "tsetmc"),
        ("delete_periodictask", "tsetmc"),
        ("view_periodictask", "tsetmc"),
        ("view_stock", "tsetmc"),
        ("view_usertask", "tsetmc"),
    ]
    permissions = [Permission.objects.get(codename=codename, content_type__app_label=app_label)
                   for codename, app_label in permission_codenames]
    group = Group.objects.create(**data)
    group.permissions.set(permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('tsetmc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_analyst_group,
                             reverse_code=migrations.RunPython.noop)
    ]
