# Generated by Django 4.0 on 2022-07-17 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, help_text='TSETMC uses this id as a unique identifier for stocks.', max_length=30)),
                ('tsetmc_symbol', models.CharField(blank=True, max_length=50)),
                ('codal_symbol', models.CharField(blank=True, max_length=50)),
                ('mycodal_id', models.CharField(blank=True, help_text='mycodal_id is an id that mycodal.ir uses as a unique identifier for companies.', max_length=10)),
                ('tsetmc_url', models.URLField(blank=True, max_length=500, null=True)),
                ('codal_url', models.URLField(blank=True, max_length=500, null=True)),
                ('codal_documents_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mycodal_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mycodal_documents_url', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('isin', models.CharField(blank=True, help_text='codal.ISIN is the same as tsetmc.Instrument_id', max_length=30)),
                ('isic', models.CharField(blank=True, help_text='codal.ISIC is one of the ids codal.ir uses as a unique identifier for companies.', max_length=30)),
                ('ci_sin', models.CharField(blank=True, help_text='tsetmc uses this id to store shareholders information.', max_length=30, verbose_name='ci_sin')),
                ('company_type', models.CharField(blank=True, max_length=200)),
                ('essence', models.CharField(blank=True, max_length=200)),
                ('acceptance_type', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('base_volume', models.PositiveIntegerField(default=0)),
                ('registered_capital', models.PositiveBigIntegerField(default=0)),
                ('unregistered_capital', models.PositiveBigIntegerField(default=0)),
                ('documents_last_updated', models.DateTimeField(default=None, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('financial_end_of_year_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('financial_end_of_year_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TickerShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.PositiveBigIntegerField()),
                ('shares_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('change', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.shareholder')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.institution')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='board_of_directors',
            field=models.ManyToManyField(blank=True, to='resources.Director'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.industrygroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='shareholders',
            field=models.ManyToManyField(through='resources.TickerShare', to='resources.ShareHolder'),
        ),
        migrations.AddField(
            model_name='company',
            name='similar_companies',
            field=models.ManyToManyField(blank=True, to='resources.Company'),
        ),
    ]
