# Generated by Django 4.0 on 2022-07-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='index',
            new_name='tsetmc_index',
        ),
    ]
