# Generated by Django 4.0 on 2022-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_rename_index_company_tsetmc_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tsetmc_old_indexes',
            field=models.JSONField(default=list),
        ),
    ]
