# Generated by Django 4.0 on 2022-07-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_company_tsetmc_old_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry_group',
        ),
        migrations.AddField(
            model_name='company',
            name='mycodal_industry_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mycodal_companies', related_query_name='mycodal_companies', to='resources.industrygroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='tsetmc_industry_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsetmc_companies', related_query_name='tsetmc_companies', to='resources.industrygroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='tsetmc_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
