# Generated by Django 4.0 on 2022-08-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_company_industry_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateIndividualEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('individual_buy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('corporate_buy_count', models.PositiveIntegerField(blank=True, null=True)),
                ('individual_sell_count', models.PositiveIntegerField(blank=True, null=True)),
                ('corporate_sell_count', models.PositiveIntegerField(blank=True, null=True)),
                ('individual_buy_volume', models.PositiveBigIntegerField(blank=True, null=True)),
                ('corporate_buy_volume', models.PositiveBigIntegerField(blank=True, null=True)),
                ('individual_sell_volume', models.PositiveBigIntegerField(blank=True, null=True)),
                ('corporate_sell_volume', models.PositiveBigIntegerField(blank=True, null=True)),
                ('individual_buy_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('corporate_buy_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('individual_sell_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('corporate_sell_value', models.PositiveBigIntegerField(blank=True, null=True)),
                ('individual_buy_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('corporate_buy_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('individual_sell_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('corporate_sell_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ownership_change', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
            ],
        ),
    ]
