# Generated by Django 4.0 on 2022-08-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_corporateindividualentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corporateindividualentry',
            unique_together={('company', 'date')},
        ),
    ]
