# Generated by Django 4.0 on 2022-08-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_pricemodification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalIncrease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prev_stocks', models.IntegerField()),
                ('next_stocks', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
    ]
