# Generated by Django 4.0 on 2022-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_capitalincrease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalincrease',
            name='next_stocks',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='capitalincrease',
            name='prev_stocks',
            field=models.BigIntegerField(),
        ),
    ]
