# Generated by Django 4.0 on 2022-09-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_company_tsetmc_market_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.PositiveIntegerField()),
                ('high', models.PositiveIntegerField()),
                ('low', models.PositiveIntegerField()),
                ('adj_close', models.PositiveIntegerField()),
                ('value', models.PositiveBigIntegerField()),
                ('volume', models.PositiveBigIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('close', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
    ]
