# Generated by Django 4.0 on 2022-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_tickerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='shareholder_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tickershare',
            name='change',
            field=models.BigIntegerField(default=0),
        ),
    ]
